remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: PrestaShop Security Advisories by 202 ecommerce
description: Knowledge Base and CVE about PrestaShop modules security issues
